import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:app/features/matches/domain/entities/match.dart';
import 'package:app/features/matches/domain/entities/team.dart';
import 'package:app/features/matches/domain/entities/match_enums.dart';
import 'package:app/features/matches/domain/repositories/match_repository.dart';
import 'package:app/features/matches/infrastructure/repositories/supabase_match_repository.dart';
import 'package:app/features/players/domain/repositories/player_repository.dart';
import 'package:app/features/players/domain/repositories/ranking_repository.dart';
import 'package:app/features/players/infrastructure/repositories/supabase_player_repository.dart';
import 'package:app/features/players/infrastructure/repositories/supabase_ranking_repository.dart';

class CreateMatchUseCase {
  final MatchRepository _matchRepository;
  final RankingRepository _rankingRepository;
  final PlayerRepository _playerRepository;

  CreateMatchUseCase(
    this._matchRepository,
    this._rankingRepository,
    this._playerRepository,
  );

  Future<Match> execute({
    required String squadId,
    required List<String> homePlayerIds,
    required List<String> awayPlayerIds,
    String? homeTeamName,
    String? awayTeamName,
    String? homeTeamColor,
    String? awayTeamColor,
    String? tournamentId,
  }) async {
    // 1. Fetch all players to have current state (especially ranking/score)
    // We can optimize this by fetching by IDs if repository supports it,
    // otherwise fetch all squad players and filter (or loop getPlayer).
    // Given ID list is small, loop getPlayer is okay, but concurrent is better.
    // Or we assume getSquadPlayers is cached/fast.
    // Let's loop getPlayer for correctness or add getPlayersByIds to repo.
    // Existing repo has getPlayer.

    final homePlayersFutures = homePlayerIds.map((id) => _playerRepository.getPlayer(playerId: id));
    final awayPlayersFutures = awayPlayerIds.map((id) => _playerRepository.getPlayer(playerId: id));

    final homePlayers = await Future.wait(homePlayersFutures);
    final awayPlayers = await Future.wait(awayPlayersFutures);

    // 2. Construct Teams
    // IDs are generated by Repository on insert, but we need to pass Team objects.
    // The Team entity has teamId required. We can generate temporary ones or let repo handle it.
    // The repository implementation generates new UUIDs.
    // But we need to pass a Team object which requires an ID. 
    // Let's generate them here or pass empty strings and let repo overwrite.
    // Repo implementation: "final homeTeamId = const Uuid().v4();" -> it ignores passed ID.
    // So we can pass placeholder.

    final homeTeam = Team(
      teamId: '', // placeholder
      matchId: '', // placeholder
      side: Side.home,
      name: homeTeamName,
      color: homeTeamColor,
      players: homePlayers,
    );

    final awayTeam = Team(
      teamId: '', // placeholder
      matchId: '', // placeholder
      side: Side.away,
      name: awayTeamName,
      color: awayTeamColor,
      players: awayPlayers,
    );

    // 3. Create Match
    final match = await _matchRepository.createMatch(
      squadId: squadId,
      tournamentId: tournamentId,
      homeTeam: homeTeam,
      awayTeam: awayTeam,
    );

    // 4. Create Ranking Entries
    // We need to use the current score of players (from step 1)
    
    final allPlayers = [...homePlayers, ...awayPlayers];
    final rankingFutures = allPlayers.map((player) {
      return _rankingRepository.createMatchRankingEntry(
        playerId: player.playerId,
        matchId: match.matchId,
        currentRanking: player.ranking,
      );
    });

    await Future.wait(rankingFutures);

    return match;
  }
}

final createMatchUseCaseProvider = Provider<CreateMatchUseCase>((ref) {
  return CreateMatchUseCase(
    ref.read(matchRepositoryProvider),
    ref.read(rankingRepositoryProvider),
    ref.read(playerRepositoryProvider),
  );
});

