import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:app/features/matches/domain/entities/match.dart';
import 'package:app/features/matches/domain/entities/team.dart';
import 'package:app/features/matches/domain/entities/match_enums.dart';
import 'package:app/features/matches/domain/repositories/match_repository.dart';
import 'package:app/features/matches/domain/repositories/team_repository.dart';
import 'package:app/features/matches/matches_providers.dart';
import 'package:app/features/players/domain/repositories/player_repository.dart';
import 'package:app/features/players/domain/repositories/ranking_repository.dart';
import 'package:app/features/players/domain/entities/player.dart';
import 'package:app/features/players/players_providers.dart';

class CreateMatchUseCase {
  final MatchRepository _matchRepository;
  final TeamRepository _teamRepository;
  final RankingRepository _rankingRepository;
  final PlayerRepository _playerRepository;

  CreateMatchUseCase(
    this._matchRepository,
    this._teamRepository,
    this._rankingRepository,
    this._playerRepository,
  );

  Future<Match> execute({
    required String squadId,
    required List<String> homePlayerIds,
    required List<String> awayPlayerIds,
    List<String> rankingHistoryPlayerIds = const [],
    bool createRankingEntries = true,
    String? homeTeamName,
    String? awayTeamName,
    String? homeTeamColor,
    String? awayTeamColor,
    String? tournamentId,
    Map<String, dynamic>? scoreMeta,
  }) async {
    // 1. Fetch all players to have current state (especially ranking/score)
    // We can optimize this by fetching by IDs if repository supports it,
    // otherwise fetch all squad players and filter (or loop getPlayer).
    // Given ID list is small, loop getPlayer is okay, but concurrent is better.
    // Or we assume getSquadPlayers is cached/fast.
    // Let's loop getPlayer for correctness or add getPlayersByIds to repo.
    // Existing repo has getPlayer.

    final homePlayersFutures = homePlayerIds.map(
      (id) => _playerRepository.getPlayer(playerId: id),
    );
    final awayPlayersFutures = awayPlayerIds.map(
      (id) => _playerRepository.getPlayer(playerId: id),
    );

    final homePlayers = await Future.wait(homePlayersFutures);
    final awayPlayers = await Future.wait(awayPlayersFutures);

    // 2. Construct Teams
    // IDs are generated by Repository on insert, but we need to pass Team objects.
    // The Team entity has teamId required. We can generate temporary ones or let repo handle it.
    // The repository implementation generates new UUIDs.
    // But we need to pass a Team object which requires an ID.
    // Let's generate them here or pass empty strings and let repo overwrite.
    // Repo implementation: "final homeTeamId = const Uuid().v4();" -> it ignores passed ID.
    // So we can pass placeholder.

    final homeTeam = Team(
      teamId: '', // placeholder
      matchId: '', // placeholder
      side: Side.home,
      name: homeTeamName,
      color: homeTeamColor ?? '#FFFFFF',
      players: homePlayers,
    );

    final awayTeam = Team(
      teamId: '', // placeholder
      matchId: '', // placeholder
      side: Side.away,
      name: awayTeamName,
      color: awayTeamColor ?? '#000000',
      players: awayPlayers,
    );

    // 3. Create Match
    final match = await _matchRepository.createMatch(
      squadId: squadId,
      tournamentId: tournamentId,
      scoreMeta: scoreMeta,
      homeTeam: homeTeam,
      awayTeam: awayTeam,
    );

    // 4. Create Teams
    await _teamRepository.createTeams(
      matchId: match.matchId,
      homeTeam: homeTeam,
      awayTeam: awayTeam,
      tournamentId: tournamentId,
    );

    final allPlayers = [...homePlayers, ...awayPlayers];
    if (allPlayers.isNotEmpty) {
      await _matchRepository.refreshMatchWinProbability(matchId: match.matchId);
    }

    final rankingEntryPlayerIds = createRankingEntries
        ? <String>{
            ...rankingHistoryPlayerIds,
            if (rankingHistoryPlayerIds.isEmpty) ...homePlayerIds,
            if (rankingHistoryPlayerIds.isEmpty) ...awayPlayerIds,
          }.toList(growable: false)
        : const <String>[];

    if (rankingEntryPlayerIds.isNotEmpty) {
      final playersById = <String, Player>{
        for (final player in allPlayers) player.playerId: player,
      };
      final missingIds = rankingEntryPlayerIds
          .where((playerId) => !playersById.containsKey(playerId))
          .toList(growable: false);
      if (missingIds.isNotEmpty) {
        final missingPlayers = await Future.wait(
          missingIds.map(
            (playerId) => _playerRepository.getPlayer(playerId: playerId),
          ),
        );
        for (final player in missingPlayers) {
          playersById[player.playerId] = player;
        }
      }

      final rankingFutures = rankingEntryPlayerIds.map((playerId) {
        final player = playersById[playerId];
        return _rankingRepository.createMatchRankingEntry(
          playerId: playerId,
          matchId: match.matchId,
          currentRanking: player!.ranking,
        );
      });

      await Future.wait(rankingFutures);
    }

    return match;
  }
}

final createMatchUseCaseProvider = Provider<CreateMatchUseCase>((ref) {
  return CreateMatchUseCase(
    ref.read(matchRepositoryProvider),
    ref.read(teamRepositoryProvider),
    ref.read(rankingRepositoryProvider),
    ref.read(playerRepositoryProvider),
  );
});
